services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data/:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
    ports:
      - "1883:1883"
    networks:
      - red-iot
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - red-iot
  
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - "./data:/var/lib/influxdb"
    environment:
      - INFLUXDB_DB=db0
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123456
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=123456789
      - DOCKER_INFLUXDB_INIT_ORG=iotlab
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket0
    networks:
      - red-iot
  
  telegraf:
    container_name: telegraf
    image: telegraf
    depends_on:
      - influxdb
      - mosquitto
    volumes:
      - "./telegraf:/etc/telegraf"
    networks:
      - red-iot

networks:
  red-iot:
    external: true